"
As an Admin of the Payroll System
I want to manage employed people
So that they I can pay them properly for their work, nothing more, nothing less.
"
Class {
	#name : #ManageEmployees,
	#superclass : #TomeFeature,
	#category : #'Payroll-AcceptanceCriteria'
}

{ #category : #scenario }
ManageEmployees >> Add_a_new_employee [
]

{ #category : #scenario }
ManageEmployees >> Change_employee_details [
]

{ #category : #scenario }
ManageEmployees >> Deleting_an_employee [
]
