name: Payroll ST CI

on: [push, pull_request, workflow_dispatch]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
  #Test:

  Deploy:
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vitormcruz/payroll-st-web/latest



