name: Payroll ST CI

on: [push, pull_request, workflow_dispatch]

jobs:

  Build:
    runs-on: ubuntu-latest
    container: vitormcruz/pharo:9
    steps:
      - uses: actions/checkout@v2
      - name: Build Payroll ST WEB Production Bin
        run: |
          pharo /opt/pharo/Pharo.image st --save --quit loadForProduction.st;
          
      - name: Save builded payroll-st-web-bin
        uses: actions/upload-artifact@v2.2.4
        with:
          name: payroll-st-web-bin
          path: /opt/pharo/Pharo.image
          if-no-files-found: error
                 
  Test:
    runs-on: ubuntu-latest
    container: vitormcruz/pharo:9
    needs: [Build]
    steps:
      - uses: actions/checkout@v2
      - name: Load builded payroll-st-web-bin
        uses: actions/download-artifact@v2.0.10
        with:
          name: payroll-st-web-bin
          path: /opt/                 #Should be /opt/pharo/, but will use a new image since Metacello cannot load Baselines incrementally. Will think later what to do about this

      - name: Load Tests
        run: pharo /opt/pharo/Pharo.image st --save --quit loadForTesting.st;

      - name: Run Tests of Payroll ST WEB
        run: pharo /opt/pharo/Pharo.image test Payroll* --junit-xml-output --fail-on-failure --fail-on-error;

  Deploy:
      runs-on: ubuntu-latest
      needs: [Test]
      steps:
        - uses: actions/checkout@v2

        - name: Load builded payroll-st-web-bin
          uses: actions/download-artifact@v2.0.10
          with:
            name: payroll-st-web-bin
            path: ${{ GITHUB_WORKSPACE }}//payroll_st//

        - name: Trace
          run: ls -la

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USER }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

        - uses: docker/build-push-action@v2
          with:
            push: true
            tags: vitormcruz/payroll-st-web:latest



